### ISSUE TITLE
[FIX] Khoj outputs chinese characters as raw unicode in a codeblock and many words are misspell

### ISSUE THREAD

**Issue by ihorizons2022** [khoj-ai/khoj#793] opened 2024-06-02 03:36 UTC
## Describe the bug
A clear and concise description of what the bug is. Please include what you were expecting to happen vs. what actually happened.
<img width="928" alt="image" src="https://github.com/khoj-ai/khoj/assets/121672603/1aa94e26-4ad6-4d64-a123-4f11e2d2a40e">

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [ ] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

**Comment by debanjum** [comment] 2024-06-02 06:43
Oh that's a strange output. The issue seems to be with Khoj rendering chinese characters as raw unicode strings in a code block?

Is it doing this consistently for you? Are you using Khoj cloud?

**Comment by debanjum** [comment] 2024-06-02 10:54
Did you by any chance request Khoj to output json in a codeblock or something in your conversation with Khoj previously? I wonder if that's why it chose to output in a codeblock. As the chat conversation screenshot you shared doesn't indicate anything about outputting json codeblocks (as far as I can tell)

**Comment by debanjum** [comment] 2024-06-03 13:38
Can you clarify what you mean? Why do you think your conversation with Khoj is using gpt-3.5? Khoj shouldn't normally switch the model on you, unless you do it yourself

**Comment by debanjum** [comment] 2024-06-03 13:47
I see, so when using gpt-3.5 the outputs aren't great for chinese (+json)? That makes sense. Just stick to gpt-4 for that use-case I guess.

Do you see any actionable item on the Khoj codebase for this? Otherwise I'll close this issue

**Comment by debanjum** [comment] 2024-06-13 13:52
No, Khoj shouldn't change the model automatically when rate limits are hit. It should just tell you to upgrade or try again tomorrow.

Not sure why you're seeing unicode style outputs in codeblocks after several rounds of chat. If you can share the text of a complete conversation with this behavior. I can try reproduce (and fix) the behavior on my end.

**Closed as completed** 2024-06-13 13:53 UTC
Labels: fix
