### ISSUE TITLE
Issue with running Obsidian plugin using local backend

### ISSUE THREAD

**Issue by edbock** [khoj-ai/khoj#615] opened 2024-01-16 17:17 UTC
I'm super impressed by how quickly you are making improvements to this incredible app.

Does the [1,000-file issue](https://github.com/khoj-ai/khoj/issues/606) affect the local backend as well? When I use http://127.0.0.1:42110 and the API key generated in the desktop app, I try syncing and get the following:

Khoj: Updating Khoj content index...
plugin:khoj:4455     POST http://127.0.0.1:42110/api/v1/index/update?force=false&client=obsidian 400 (Bad Request)
updateContentIndex @ plugin:khoj:4455
await in updateContentIndex (async)
eval @ plugin:khoj:6274

I am working around this by using the add folders function to add subfolders in my vault one at a time, but this has obvious disadvantages.

**Comment by debanjum** [comment] 2024-01-16 19:18
Hey @edbock yes, the 1000 file issue affects both self-hosted and cloud versions of Khoj server. This is why you're seeing the `400 (Bad request)` error. The way you're indexing your vault is the best mitigation for now. We'll do a release in a day or so with [the fix](https://github.com/khoj-ai/khoj/pull/605) for this issue, at which point this annoyance should go away.

I'll close this issue as it's a duplicate of the [1000 file issue](https://github.com/khoj-ai/khoj/issues/573)

**Closed by debanjum** 2024-01-16 19:18 UTC
