### ISSUE TITLE
khoj.el: Failed to force update all  content index. Status: http 400. Response: {"detail":"There was an error parsing the body"}

### ISSUE THREAD

**Issue by HyunggyuJang** [khoj-ai/khoj#602] opened 2024-01-07 05:57 UTC
Met this error from (the latest) emacs client. Tried with self-hosted server, setup with docker.

Confirmed that this persists also for khoj cloud server.

**Comment by debanjum** [comment] 2024-01-10 04:09
Hey @HyunggyuJang, thanks for sharing the issue and clarifying that it persists across self-hosted with docker and khoj cloud.

Can you share how you've configured Khoj in your emacs config (`init.el`)?

**Comment by HyunggyuJang** [comment] 2024-01-12 00:56
Sure, here it is
```elisp
  (use-package khoj
    :after org
    :config (setq khoj-index-directories (list org-directory)
                  khoj-index-files nil
                  khoj-api-key <api-key>))
```
For the khoj cloud usage, and
```elisp
  (use-package! khoj
    :after org
    :config (setq khoj-index-directories (list org-directory)
                  khoj-index-files nil
                  khoj-server-url "http://127.0.0.1:42110"
                  khoj-api-key <api-key>))
```
for self host.

**Comment by debanjum** [comment] 2024-02-21 07:38
Hey @HyunggyuJang, could you check if the issue is resolved for you with the the latest `khoj.el`?  The indexing error should have been fixed in 392df40f361b76ef343f3653289f4d20085093c0.

**Comment by HyunggyuJang** [comment] 2024-02-26 04:48
Thanks! I will check it.

**Comment by debanjum** [comment] 2024-03-09 22:19
Hey @HyunggyuJang I'll mark this issue as closed for now. Please feel free to reopen it if you are still hitting this issue

**Closed by debanjum** 2024-03-09 22:19 UTC
Labels: fix, question
