### ISSUE TITLE
Bugs? 

### ISSUE THREAD

**Issue by Gypsyaus** [khoj-ai/khoj#742] opened 2024-05-23 03:14 UTC
- [ ] ![Screenshot_20240509-071808.png](https://github.com/khoj-ai/khoj/assets/170590680/85b47b4e-5c62-4cb7-baa4-891f88ae776e)

**Comment by sabaimran** [comment] 2024-05-23 03:35
Hi @Gypsyaus , can you clarify what you did that led you here, and what are we looking at?

**Comment by Gypsyaus** [comment] 2024-05-23 03:38
My phone was being weird n I managed to get into the system and came across the tasks and codes as a result. Was amused due to the fact the times and commands didn't match the times I was using the device.

**Comment by sabaimran** [comment] 2024-05-23 22:35
Was this one the web view on your mobile browser? Some additional context would be helpful, I'm not super clear on what the problem is here.

**Comment by sabaimran** [comment] 2024-06-01 16:28
Hey @Gypsyaus , I'm going to close this out as it seems like a false alarm.

**Closed by sabaimran** 2024-06-01 16:28 UTC
