### ISSUE TITLE
does not work on ubuntu: version `GLIBC_2.35' not found

### ISSUE THREAD

**Issue by kforner** [khoj-ai/khoj#378] opened 2023-07-31 12:30 UTC
After installation using the latest debian package `khoj_0.10.0_amd64.deb`:

```
/opt/Khoj 
[39318] SPLASH: Failed to load Tcl/Tk libraries!
[39326] Error loading Python lib '/tmp/_MEIJcR2vd/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIJcR2vd/libpython3.9.so.1.0)
```

```
uname -a
Linux valhalla 5.19.17-051917-generic #202210240939 SMP PREEMPT_DYNAMIC Mon Oct 24 09:43:01 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

▶ dpkg -l | grep "Python language"
ii  libpython2.7-minimal:amd64                                  2.7.18-1~20.04.3                           amd64        Minimal subset of the Python language (version 2.7)
ii  libpython3.5-minimal:amd64                                  3.5.2-2ubuntu0~16.04.4                     amd64        Minimal subset of the Python language (version 3.5)
rc  libpython3.6-minimal:amd64                                  3.6.9-1~18.04                              amd64        Minimal subset of the Python language (version 3.6)
rc  libpython3.7-minimal:amd64                                  3.7.5-2~19.10ubuntu1                       amd64        Minimal subset of the Python language (version 3.7)
ii  libpython3.8-minimal:amd64                                  3.8.10-0ubuntu1~20.04.7                    amd64        Minimal subset of the Python language (version 3.8)
ii  python2.7-minimal                                           2.7.18-1~20.04.3                           amd64        Minimal subset of the Python language (version 2.7)
ii  python3-minimal                                             3.8.2-0ubuntu2                             amd64        minimal subset of the Python language (default python3 version)
ii  python3.5-minimal                                           3.5.2-2ubuntu0~16.04.4                     amd64        Minimal subset of the Python language (version 3.5)
rc  python3.6-minimal                                           3.6.9-1~18.04                              amd64        Minimal subset of the Python language (version 3.6)
rc  python3.7-minimal                                           3.7.5-2~19.10ubuntu1                       amd64        Minimal subset of the Python language (version 3.7)
ii  python3.8-minimal                                           3.8.10-0ubuntu1~20.04.7                    amd64        Minimal subset of the Python language (version 3.8)
```

**Comment by sabaimran** [comment] 2023-08-02 17:47
Thanks for raising the issue (with relevant details!) and sorry for the installation roadblocks. As it turns out, `GLIBC_2.35` isn't available on Ubuntu 20.04 -- as showing in [this](https://askubuntu.com/questions/1408049/how-can-i-get-glibc-2-35-on-ubuntu-20-04) and [this](https://fluka-forum.web.cern.ch/t/version-glibc-2-35-not-found/3694) discussion.

For now, I think Ubuntu 22.04 is just going to be a system requirement. I'll document that some place.

You should still be able to use the application via the python package, but let me know if that doesn't work either.

**Comment by kforner** [comment] 2023-08-03 07:05
> You should still be able to use the application via the python package

no. cf https://github.com/khoj-ai/khoj/issues/391

**Comment by kforner** [comment] 2023-08-03 07:07
> For now, I think glibc 2.35 is just going to be a system requirement. I'll document that some place.

ubuntu 20.04 is a LTS, meaning lots of people and enterprises still use it.

Thanks for your help.

**Comment by debanjum** [comment] 2023-08-07 06:45
Hey @kforner, I was able to finally reproduce this issue on an Ubuntu 20.04.

Can you verify that using a development version of the khoj debian package from [here](https://github.com/khoj-ai/khoj/actions/runs/5781741914) fixes the issue for you?

**Comment by kforner** [comment] 2023-08-08 09:43
Hey.  I could not find any deb package in your link.

**Comment by debanjum** [comment] 2023-08-09 06:45
Ah those build artifacts have expired. Could you try install the `.deb` package visible at the bottom of [this build](https://github.com/khoj-ai/khoj/actions/runs/5805453424)?
Or if that's expired (in 3 days from today) a `.deb` package from the latest desktop app build [here](https://github.com/khoj-ai/khoj/actions/workflows/build_desktop.yml)

**Comment by kforner** [comment] 2023-08-09 06:52
This almost worked:
```
/opt/Khoj 
[08:52:05 AM] INFO     🌘 Starting Khoj                                                                                                                                    main.py:69
/opt/Khoj: symbol lookup error: /tmp/_MEI977qgB/libQt6WaylandClient.so.6: undefined symbol: wl_proxy_marshal_flags

```

**Comment by debanjum** [comment] 2023-08-14 23:46
One slow step at a time to support Ubuntu 20.04. Which version of Wayland do you have installed on your machine?

The default wayland on your Ubuntu 20.04 seems to have an older version installed (<1.19.91) and PySide >= 6.5.1 which Khoj uses expects a newer wayland than that, which supports `wl_proxy_marshal_flags`. Potential solutions:
* You can try the wayland on your Ubuntu to >= 1.19.91
* One of us can find out which PySide6 version works with the default wayland version installed on Ubuntu and verify Khoj works with that version of PySide6. We can then pin Khoj to use that Pyside6 version

**Comment by debanjum** [comment] 2023-10-17 01:01
Closing this issue as we've removed dependency from PySide for the Khoj GUI/Desktop app

**Closed by debanjum** 2023-10-17 01:01 UTC
Labels: fix, question
