### ISSUE TITLE
[FIX] Docker version: Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by saccohuo** [khoj-ai/khoj#881] opened 2024-08-05 16:02 UTC
## Describe the bug
Open localhost:42110, after a flash of  some window, then get the blank page with error `Application error: a client-side exception has occurred (see the browser console for more information).` 

In the console, shows `fd9d1056-2b978342deb60015.js:1 Error: <svg> attribute height: Expected length`.

## Screenshots

![image](https://github.com/user-attachments/assets/e321ba61-467e-45f9-8e60-d184eda08604)

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [x] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [x] Web browser
    - [ ] WhatsApp
- OS:
    - [x] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]: I cannot get the version.

**Comment by rogerc66** [comment] 2024-08-06 17:57
Same here

**Comment by PiyushDixit96** [comment] 2024-08-09 04:55
> ## Describe the bug
> 
> Open localhost:42110, after a flash of some window, then get the blank page with error `Application error: a client-side exception has occurred (see the browser console for more information).`
> 
> In the console, shows `fd9d1056-2b978342deb60015.js:1 Error: <svg> attribute height: Expected length`.
> ## Screenshots
> 
> ![image](https://private-user-images.githubusercontent.com/13887263/355167986-e321ba61-467e-45f9-8e60-d184eda08604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzk1MzksIm5iZiI6MTcyMzE3OTIzOSwicGF0aCI6Ii8xMzg4NzI2My8zNTUxNjc5ODYtZTMyMWJhNjEtNDY3ZS00NWY5LThlNjAtZDE4NGVkYTA4NjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA0NTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NTRhZGM1YzgyOTZlMTgyNDY3YzA2MDY3ZDVmZTBiYWM2YzQ0ZmY1OTc1MTgyNGMxYmRlMWY1MWE4YmM2YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._hnTb8gZfTNCm2YZ8FGz8XB3vOvgCDVnHwDlOIp_FXs)
> ## Platform
> 
>     * Server:
>       
>       * [ ]  Cloud-Hosted (https://app.khoj.dev)
>       * [x]  Self-Hosted Docker
>       * [ ]  Self-Hosted Python package
>       * [ ]  Self-Hosted source code
> 
>     * Client:
>       
>       * [ ]  Obsidian
>       * [ ]  Emacs
>       * [ ]  Desktop app
>       * [x]  Web browser
>       * [ ]  WhatsApp
> 
>     * OS:
>       
>       * [x]  Windows
>       * [ ]  macOS
>       * [ ]  Linux
>       * [ ]  Android
>       * [ ]  iOS
> 
> 
> ### If self-hosted
> 
>     * Server Version [e.g. 1.0.1]: I cannot get the version.
> 
> 
> ## Additional context
> 
> Add any other context about the problem here.

Hello.
I am also getting same error.

**Comment by PiyushDixit96** [comment] 2024-08-09 05:00
issue fix update this value in docker-compose.yml
KHOJ_DEBUG=True
and upgrade the build
docker-compose up --build

please try this

**Comment by rogerc66** [comment] 2024-08-09 06:40
> issue fix update this value in docker-compose.yml KHOJ_DEBUG=True and upgrade the build docker-compose up --build
> 
> please try this

No luck, still get the same error after rebuild

**Comment by Miskina** [comment] 2024-08-09 08:55
Hello I am having the same problem on Debian Bookworm (self-hosting with Docker).
It seems the problem is in the [page.tsx:114](https://github.com/khoj-ai/khoj/blob/5ef198a5b2ec01d4925a1a6359715d09bfec5560/src/interface/web/app/page.tsx#L114) file of the web frontend. Specifically one of the agents in the `agents` array seems to be undefined which in turn causes the error. I'm not sure what the root cause of it is, but modifying the code from:

```typescript
        const agentIcons = agents.map(
            (agent) =>
                getIconFromIconName(agent.icon, agent.color) || (
                    <Image
                        key={agent.name}
                        src={agent.avatar}
                        alt={agent.name}
                        width={50}
                        height={50}
                    />
                ),
        );
``` 
to:

```typescript
        const agentIcons = agents.filter(agent => agent !== null && agent !== undefined).map(
            (agent) =>
                getIconFromIconName(agent.icon, agent.color) || (
                    <Image
                        key={agent.name}
                        src={agent.avatar}
                        alt={agent.name}
                        width={50}
                        height={50}
                    />
                ),
        );
``` 

seems to work. Of course you need to make the docker-compose build from source instead of pull the image for the changes to take effect.

**Comment by sabaimran** [comment] 2024-08-10 07:53
Hey folks! Sorry about this, let me push a fix for this. This should also be resolved if you setup a chat model configuration and restart your server. Thanks for the root cause discovery, @Miskina !

**Comment by rogerc66** [comment] 2024-08-10 10:21
> Hey folks! Sorry about this, let me push a fix for this. This should also be resolved if you setup a chat model configuration and restart your server. Thanks for the root cause discovery, @Miskina !

Hi, Sabi

Can you please tell us how to setup a chat model config in docker compose? by adding a environment parameter or what ? Thank you.

**Comment by saccohuo** [comment] 2024-08-12 17:02
@sabaimran Hi, the 1.20.4 version solves the problem, but I get `Bad Request (400)` when I visit `http://<myip>:42110/server/admin`.

**Comment by rogerc66** [comment] 2024-08-14 06:34
> @sabaimran Hi, the 1.20.4 version solves the problem, but I get `Bad Request (400)` when I visit `http://<myip>:42110/server/admin`.

I'm having the same problem, blank 400 page for /server/admin

**Comment by saccohuo** [comment] 2024-08-24 02:12
@sabaimran Hi, could you please fix this problem? Many thanks.

**Comment by sabaimran** [comment] 2024-08-24 21:11
I'll make some time to look into it today or tomorrow @saccohuo . You're able to load the rest of the app, right?

**Comment by saccohuo** [comment] 2024-08-25 05:14
> I'll make some time to look into it today or tomorrow @saccohuo . You're able to load the rest of the app, right? And are you able to load it on `localhost`, or is it always returning a bad request 400? Some more details about your setup will be helpful to debug.我会在今天或明天抽时间来看看这个问题 @saccohuo。你能加载应用的其他部分吗？你能在 `localhost` 上加载吗，还是总是返回错误请求 400？关于你的设置的更多细节将有助于调试。

After `Application error: a client-side exception has occurred (see the browser console for more information).` problem solved, I get 400 at `http://<myip>:42110/server/admin`.
I cannot set the model, so I cannot do anything to it.

**Comment by saccohuo** [comment] 2024-09-03 08:28
@sabaimran Hi, is any update?

**Comment by debanjum** [comment] 2024-09-21 21:37
Hi folks, this issue seems to contain 2 separate issues, both of which should be resolved:
1. The original Application error issue seems to have resolved
2. The admin panel not being accessible and showing Bad Request (400) when trying to be accessed over external i.p (instead of localhost)

On issue 2. @saccohuo, 
- I was able to access Khoj web app and web admin panel with Khoj being run on Windows + WSL2 + Docker
- I was also able to access the admin panel over an external i.p or domain like `http://<myip>:42110/server/admin` when run from PR #919.

> I get Bad Request (400) when I visit http://<myip>:42110/server/admin.

I can reproduce the Bad Request (400) page when trying to access the server admin page when the `KHOJ_DOMAIN` environment variable in the `docker-compose.yml` isn't (correctly) set to `<myip>`. This issue can be resolved by setting the environment variable `KHOJ_DOMAIN=<myip>` in your `docker-compose.yml`

## Next Steps
> for folks who got stuck trying to setup their Khoj server for remote access
  1. Delete your Khoj docker container, images and volumes (with `docker-compose down --volumes`)
  2. Get the latest Khoj [docker-compose.yml ](https://github.com/khoj-ai/khoj/blob/master/docker-compose.yml). The Docker setup has been simplified in #919 using self hosted Khoj
  3. Edit the downloaded khoj docker-compose.yml for Remote Access and Chat Models you want to enable by default. See the new [Remote Access Doc](http://localhost:3000/advanced/remote) and the updated [Self Hosting Setup Docs](http://localhost:3000/get-started/setup?os=windows&server=docker) for details
  4. Now startup Khoj by running `docker-compose up`

I'm closing this issue as the original bug has been resolved.
Feel free to create a new issue if you're still facing problems with remote access. Details on how you tried to setup Khoj (OS, Docker vs Pip) and what error you're seeing (screenshots or server logs) would be useful to troubleshoot

**Closed by debanjum** 2024-09-21 21:37 UTC
Labels: fix, docker
